from flask import Flask, render_template, request
"""
This module defines a simple Flask web application with two routes.
Routes:
    /: Renders the home page (index.html).
    /submit: Handles form submission via POST method and displays the submitted input.
Functions:
    home(): Renders the home page.
    submit(): Handles form submission and prints the user input to the console.
Notes:
    - Ensure that the 'index.html' template exists in the 'templates' directory.
    - The application runs in debug mode for development purposes.

The initial version of this module was generated by Claude. 
"""

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/submit', methods=['POST'])
def submit():
    if request.method == 'POST':
        user_input = request.form['user_input']
        print(f"User submitted: {user_input}")  # Console output
        return f"You submitted: {user_input}"

if __name__ == '__main__':
    app.run(debug=True)

